const scenes=[
 {caption:'A common business view makes the next decision visible.',html:`<span class="micro">01 / BUSINESS SIGNAL</span><h4>Find the gap behind the headline.</h4><div class="metrics"><div class="metric"><span>ILLUSTRATIVE STORES</span><strong>120</strong></div><div class="metric"><span>ON-SHELF AVAILABILITY</span><strong>82%</strong></div><div class="metric"><span>PRIORITY STORES</span><strong>18</strong></div></div><div class="chart" role="img" aria-label="Illustrative opportunity scores: North 40, East 55, South 88, West 35"><div class="bar" style="height:40%"></div><div class="bar" style="height:55%"></div><div class="bar" style="height:88%"></div><div class="bar" style="height:35%"></div></div><div class="chart-labels"><span>North</span><span>East</span><span>South</span><span>West</span></div><p>South has the largest illustrated opportunity score.</p>`},
 {caption:'AI adds business context to a shared data foundation.',html:`<span class="micro">02 / CONTEXTUAL AI</span><h4>Ask a business question.</h4><div class="question">“Which stores should my team prioritize this week?”</div><div class="answer"><span class="micro">SCRIPTED EXAMPLE RESPONSE</span><p>Start with the 18 priority stores in South. They combine high sales potential with availability gaps.</p><p>Review stock availability and assign follow-up before expanding coverage.</p><span class="pill">Synthetic store data</span> <span class="pill">Human review</span></div>`},
 {caption:'The recommendation becomes a plan with a person and a review date.',html:`<span class="micro">03 / OWNED EXECUTION</span><h4>Give the insight an owner.</h4><div class="plan"><span>FOCUS</span><b>18 priority stores · South</b><span>OWNER</span><b>Demo territory team</b><span>ACTION</span><b>Check stock and resolve shelf gaps</b><span>BASELINE</span><b>82% on-shelf availability</b><span>REVIEW</span><b>Two weeks after plan start</b></div><p>Illustrative plan prepared for a team member to review.</p>`},
 {caption:'Measure the change, then decide what to do next.',html:`<span class="micro">04 / REVIEW & LEARN</span><h4>Close the decision loop.</h4><div class="review-row"><small>EXAMPLE METRIC</small><small>BASELINE</small><small>REVIEW</small></div><div class="review-row"><b>Availability</b><span>82%</span><b style="color:var(--lime)">91%</b></div><div class="review-row"><b>Priority stores</b><span>18</span><span>18 reviewed</span></div><div class="answer" style="margin-top:20px"><p>Review unresolved gaps and refine the next plan.</p></div><p>Fictional before/after values demonstrate review; they are not measured business results or evidence of causality.</p>`}
];
let current=0,timer=null;const play=document.getElementById('play');
function stop(){clearInterval(timer);timer=null;play.textContent='▶ Play 40-second walkthrough'}
function showScene(index){current=index;document.querySelector('.screen').innerHTML=scenes[index].html;document.getElementById('caption').textContent=scenes[index].caption;document.getElementById('counter').textContent=`0${index+1} / 04`;document.getElementById('progress').style.width=`${(index+1)*25}%`;document.querySelectorAll('.step').forEach((button,i)=>{button.classList.toggle('active',i===index);button.setAttribute('aria-pressed',String(i===index))})}
document.querySelectorAll('.step').forEach(button=>button.addEventListener('click',()=>{stop();showScene(Number(button.dataset.step))}));
play.addEventListener('click',()=>{if(timer){stop();return}showScene(0);play.textContent='Ⅱ Pause walkthrough';timer=setInterval(()=>{if(current===3){stop();return}showScene(current+1)},10000)});
showScene(0);
